resolver: lts-21.25 # ghc-9.4.8
#resolver: lts-22.6 # ghc-9.6.3  does not build due to base > 4.18
#resolver: lts-22.8 # ghc-9.6.4 does not build due to base > 4.18
packages: 
- .
extra-deps:
- ghc-tcplugin-api-0.10.0.0
- typelet-0.1.3
- primitive-0.7.4.0
- large-generics-0.2.1
- large-anon-0.3.0

